version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "postgres"
    ports:
      - "5435:5432"

  flyway:
    image: flyway/flyway
    command: "-url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -connectRetries=10 migrate"
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on:
      - postgres